
services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/ips
    ports:
      - "8001:8000"
    depends_on:
      - db
  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_USER: luz         
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: db       
    ports:
      - "5433:5432"                  
volumes:
  postgres_data: