# Generated by Django 5.1.1 on 2024-10-29 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appips', '0003_alter_usuario_codigo_pertenencia_etnica'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='codigo_pais',
        ),
        migrations.AlterField(
            model_name='usuario',
            name='codigo_nivel_educativo',
            field=models.SmallIntegerField(choices=[(1, 'Preescolar'), (10, 'Especialización'), (11, 'Maestría'), (12, 'Doctorado'), (13, 'Ninguno'), (2, 'Básica Primaria'), (3, 'Básica Secundaria'), (4, 'Media Académica o Clásica'), (5, 'Media Técnica (Bachillerato Técnico)'), (6, 'Normalista'), (7, 'Técnica Profesional'), (8, 'Tecnológica'), (9, 'Profesional')]),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='codigo_ocupacion',
            field=models.SmallIntegerField(choices=[('9611', 'Recolectores de basura y material reciclable'), ('9612', 'Clasificadores de desechos'), ('9613', 'Barrenderos y afines'), ('9621', 'Mensajeros, mandaderos, maleteros y repartidores'), ('9622', 'Personas que realizan trabajos varios'), ('9624', 'Acarreadores de agua y recolectores de leña'), ('9625', 'Recolectores de dinero y surtidores de máquinas de venta automática'), ('9626', 'Lectores de medidores'), ('9629', 'Otras ocupaciones elementales no clasificadas en otros grupos primarios'), ('9998', 'Jubilado, desempleado, ama de casa, estudiante, dedicación al hogar, menor de edad'), ('9999', 'No informa')]),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='tipo_identificacion',
            field=models.CharField(choices=[('RC', 'Registro Civil'), ('TI', 'Tarjeta De Identidad'), ('CE', 'Cédula De Extranjería'), ('CC', 'Cédula De Ciudadanía'), ('PA', 'Pasaporte'), ('MS', 'Menor Sin Identificación'), ('AS', 'Adulto Sin Identificación'), ('CD', 'Carnet Diplomático'), ('NV', 'Certificado Nacido Vivo')], max_length=2),
        ),
    ]
