# Generated by Django 5.1.1 on 2024-10-30 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appips', '0004_remove_usuario_codigo_pais_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='sexo',
            field=models.CharField(choices=[('F', 'FEMENINO'), ('M', 'MASCULINO')], max_length=1),
        ),
    ]
