# Generated by Django 5.1.1 on 2024-10-30 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appips', '0005_alter_usuario_sexo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='codigo_ocupacion',
            field=models.SmallIntegerField(choices=[(9611, 'Recolectores de basura y material reciclable'), (9612, 'Clasificadores de desechos'), (9613, 'Barrenderos y afines'), (9621, 'Mensajeros, mandaderos, maleteros y repartidores'), (9622, 'Personas que realizan trabajos varios'), (9624, 'Acarreadores de agua y recolectores de leña'), (9625, 'Recolectores de dinero y surtidores de máquinas de venta automática'), (9626, 'Lectores de medidores'), (9629, 'Otras ocupaciones elementales no clasificadas en otros grupos primarios'), (9998, 'Jubilado, desempleado, ama de casa, estudiante, dedicación al hogar, menor de edad'), (9999, 'No informa')]),
        ),
    ]
