# Generated by Django 5.1.1 on 2024-11-06 02:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appips', '0007_medico_alter_citas_medico_delete_medicos'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='sexo',
            new_name='genero',
        ),
    ]
