# Generated by Django 5.1.1 on 2024-11-20 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appips', '0008_rename_sexo_usuario_genero'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HistoriaClinica',
        ),
    ]
