# Generated by Django 5.1.1 on 2024-11-21 16:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appips', '0010_historiaclinica'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historiaclinica',
            name='cita',
        ),
        migrations.RemoveField(
            model_name='historiaclinica',
            name='diagnostico',
        ),
        migrations.RemoveField(
            model_name='historiaclinica',
            name='observaciones',
        ),
        migrations.RemoveField(
            model_name='historiaclinica',
            name='tratamiento',
        ),
        migrations.AlterField(
            model_name='historiaclinica',
            name='usuario',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='historia_clinica', to='appips.usuario'),
        ),
        migrations.CreateModel(
            name='RegistroCita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diagnostico', models.TextField()),
                ('tratamiento', models.TextField()),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('cita', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='registro_cita', to='appips.citas')),
                ('historia_clinica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros_citas', to='appips.historiaclinica')),
            ],
        ),
    ]
