# Generated by Django 5.1.1 on 2024-11-26 00:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appips', '0013_remove_usuario_edad_delete_customuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('intervalo', models.IntegerField(default=30)),
                ('medico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appips.medico')),
            ],
        ),
    ]
