# Generated by Django 5.1.1 on 2024-11-26 01:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appips', '0014_agenda'),
    ]

    operations = [
        migrations.CreateModel(
            name='HorarioCita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hora', models.TimeField()),
                ('disponible', models.BooleanField(default=True)),
                ('agenda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='horarios', to='appips.agenda')),
            ],
        ),
    ]
