# Generated by Django 5.1.1 on 2024-11-26 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appips', '0015_horariocita'),
    ]

    operations = [
        migrations.AlterField(
            model_name='citas',
            name='hora_cita',
            field=models.CharField(),
        ),
    ]
