# Generated by Django 5.1.1 on 2024-11-26 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appips', '0016_alter_citas_hora_cita'),
    ]

    operations = [
        migrations.AlterField(
            model_name='citas',
            name='hora_cita',
            field=models.TimeField(),
        ),
    ]
